package by.epam.project.controller.command;

public enum CommandName {
    AUTHORISATION, SIGN_OUT, REGISTRATION, TAKE_USER, TAKE_USERS, UPDATE_USER, UPDATE_PASSWORD, DELETE_USER,
    ADD_BOOK, TAKE_BOOK, TAKE_BOOKS, UPDATE_BOOK, DELETE_BOOK, TAKE_AUTHOR, UPDATE_AUTHOR, TAKE_USER_CARD,
    ADD_CARD_NOTE, TAKE_CARD_NOTE, TAKE_CARD_NOTES, UPDATE_CARD_NOTE, DELETE_CARD_NOTE, WRONG_REQUEST, GO_TO_PROFILE,
    TAKE_BOOK_BY_PART_OF_TITLE, CANCEL_ORDER, CHANGE_LANGUAGE
}